# -------------------------------------------------------------------
# Helm Chart 的自定义配置值
# -------------------------------------------------------------------

# MySQL 架构设置
architecture: standalone

# 全局配置
global:
  # 默认存储类名称
  defaultStorageClass: nfs

# 认证配置
auth:
  # MySQL root用户密码
  rootPassword: "YOUR_PASSWORD"
  # MySQL 数据库名称
  database: test
  # MySQL 用户名称
  username: lbs
  # MySQL 用户密码
  password: "YOUR_PASSWORD"

# Primary 节点配置
primary:
  persistence:
    size: 16Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 2048Mi

# Secondary 节点（副本集或主从模式下使用，Standalone 模式可能不适用或被忽略，但保留以防配置中存在）
secondary:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 4096Mi

# RBAC (Role-Based Access Control) 配置
rbac:
  # 设置为 true 来自动创建 RBAC 相关的资源
  create: true

# Metrics 监控配置 (Prometheus Exporter)
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    # Prometheus 监控组件所在的命名空间
    namespace: monitoring
    additionalLabels:
      # Prometheus Operator 用于发现 ServiceMonitor 的标签值
      release: kube-prom-stack
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 1024Mi

# 额外环境变量
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai
