apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: elastic-system
  name: my-kibana
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: my-es-cluster
    namespace: elastic-system
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2
#      nodeSelector:
#        type: frontend
