# -------------------------------------------------------------------
# ECK Operator Helm Chart 的自定义配置值
# -------------------------------------------------------------------

# 副本数配置
replicaCount: 1

# 镜像配置
image:
  repository: docker.elastic.co/eck/eck-operator
  pullPolicy: IfNotPresent

# 资源限制配置
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 150Mi

# Webhook 配置
webhook:
  enabled: true
  manageCerts: true

# 配置项
config:
  # 日志级别 (0: 信息级别, 1: 调试级别)
  logVerbosity: "0"
  # 最大并发协调操作数
  maxConcurrentReconciles: "3"
  # 容器镜像仓库
  containerRegistry: docker.elastic.co
  # 启用存储类验证
  validateStorageClass: true
  # 启用领导者选举
  enableLeaderElection: true
  # 指标配置
  metrics:
    # 启用指标端口
    port: "8080"

# Prometheus PodMonitor 配置
podMonitor:
  # 启用 PodMonitor
  enabled: true
  # 添加标签便于 Prometheus 发现
  labels:
    app: elastic-operator
    release: kube-prom-stack
  # 部署到 monitoring 命名空间（与你的 Prometheus 在同一命名空间）
  namespace: monitoring
  # 抓取间隔
  interval: 30s
  # 抓取超时
  scrapeTimeout: 10s
  # 将 Pod 标签转移到指标目标
  podTargetLabels:
    - app
    - version

