# -------------------------------------------------------------------
# Helm Chart 的自定义配置值
# -------------------------------------------------------------------

# MySQL 架构设置
architecture: replication

# 全局配置
global:
  # 默认存储类名称
  defaultStorageClass: "nfs"

# 认证配置
auth:
  # MySQL root用户密码
  rootPassword: "YOUR_PASSWORD"
  # MySQL 数据库名称
  database: "test"
  # MySQL 用户名称
  username: "lbs"
  # MySQL 用户密码
  password: "YOUR_PASSWORD"
  # MySQL 复制用户名称
  replicationUser: "replicator"
  # MySQL 复制用户密码
  replicationPassword: "YOUR_PASSWORD"

# 主节点（primary）配置
primary:
  persistence:
    # 持久化存储大小
    size: 16Gi
  resources:
    requests:
      # CPU 请求
      cpu: 250m
      # 内存请求
      memory: 512Mi
    limits:
      # CPU 限制
      cpu: 2000m
      # 内存限制
      memory: 4096Mi

# 从节点（secondary）配置
secondary:
  # 从节点副本数量
  replicaCount: 2
  persistence:
    # 持久化存储大小
    size: 16Gi
  resources:
    requests:
      # CPU 请求
      cpu: 250m
      # 内存请求
      memory: 512Mi
    limits:
      # CPU 限制
      cpu: 2000m
      # 内存限制
      memory: 4096Mi

# RBAC (Role-Based Access Control) 配置
rbac:
  # 设置为 true 来自动创建 RBAC 相关的资源
  create: true

# 监控配置 (metrics)
metrics:
  # 启用监控
  enabled: true
  serviceMonitor:
    # 启用 ServiceMonitor
    enabled: true
    # Prometheus 监控组件所在的命名空间
    namespace: "monitoring"
    labels:
      # Prometheus Operator 用于发现 ServiceMonitor 的标签值
      release: "kube-prom-stack"
  resources:
    requests:
      # CPU 请求
      cpu: 100m
      # 内存请求
      memory: 128Mi
    limits:
      # CPU 限制
      cpu: 256m
      # 内存限制
      memory: 1024Mi

# 额外的环境变量
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai

