# -------------------------------------------------------------------
# Helm Chart 的自定义配置值
# -------------------------------------------------------------------

# 全局配置
global:
  # 默认存储类名称
  defaultStorageClass: nfs
  # Redis 密码
  redis:
    password: YOUR_PASSWORD

# 持久化存储配置
persistence:
  # 持久化卷大小
  size: 8Gi

# Redis 节点资源限制与请求
redis:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 2048Mi

# Update Job 资源限制与请求 (用于集群扩缩容等操作)
updateJob:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 2048Mi

# RBAC (Role-Based Access Control) 配置
rbac:
  # 设置为 true 来自动创建 RBAC 相关的资源
  create: true

# 监控配置 (Prometheus Exporter)
metrics:
  # 是否启用指标导出
  enabled: true
  service:
    enabled: true
  # ServiceMonitor 配置 (用于 Prometheus Operator)
  serviceMonitor:
    # 是否启用 ServiceMonitor
    enabled: true
    # Prometheus 监控组件所在的命名空间
    namespace: monitoring
    # Prometheus Operator 用于发现 ServiceMonitor 的标签值
    additionalLabels:
      release: kube-prom-stack
  # 指标导出器资源限制与请求
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 1024Mi

# 额外环境变量
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai

