---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: flink
  name: flink-kubernetes-operator
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flink-kubernetes-operator
  podMetricsEndpoints:
    - port: metrics
