---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: flink
  name: flink-application-example
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: application-example
  podMetricsEndpoints:
    - port: metrics
