---

apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  namespace: flink
  name: application-example  # flink 集群名称
spec:
  image: flink:1.18.0-java8
  flinkVersion: v1_18
  imagePullPolicy: IfNotPresent
  ingress:
    template: "flink.lbs.com/{{namespace}}/{{name}}(/|$)(.*)"
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    state.checkpoints.dir: file:///opt/flink/checkpoints
    high-availability.type: kubernetes
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory # JobManager HA
    high-availability.storageDir: file:///opt/flink/flink_recovery  # JobManager HA数据保存路径
    jobmanager.archive.fs.dir: file:///opt/flink/flink_history      # JobManager 归档路径
    historyserver.archive.fs.dir: file:///opt/flink/flink_history      # Historyserver 归档路径
    historyserver.archive.fs.refresh-interval: "10000"              # Historyserver 文件刷新间隔
    taskmanager.memory.managed.size: 0m  # 配置托管内存为0（状态后端为内存时启用）
    rest.flamegraph.enabled: true  # 开启火焰图
  serviceAccount: flink
  jobManager:
    replicas: 2  # HA下， jobManger的副本数要大于1
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
  podTemplate:
    spec:
      hostAliases:
        - ip: "192.168.6.132"
          hostnames:
            - "master"
        - ip: "192.168.6.135"
          hostnames:
            - "node1"
        - ip: "192.168.6.136"
          hostnames:
            - "node2"
      containers:
        - name: flink-main-container
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: flink-jar  # 挂载nfs上的jar
              mountPath: /opt/flink/jar
            - name: flink-checkpoints  # 挂载checkpoint pvc
              mountPath: /opt/flink/checkpoints
              # 取消本地持久化日志，转用elk采集
#            - name: flink-log  # 挂载日志 pvc
#              mountPath: /opt/flink/log
            - name: flink-ha    # HA pvc配置
              mountPath: /opt/flink/flink_recovery
            - name: flink-historyserver # 历史服务器 pvc配置
              mountPath: /opt/flink/flink_history
      volumes:
        - name: flink-jar
          persistentVolumeClaim:
            claimName: flink-jar-pvc
        - name: flink-checkpoints
          persistentVolumeClaim:
            claimName: flink-checkpoint-application-pvc
          # 取消本地持久化日志，转用elk采集
#        - name: flink-log
#          persistentVolumeClaim:
#            claimName: flink-log-pvc
        - name: flink-ha
          persistentVolumeClaim:
            claimName: flink-ha-pvc
        - name: flink-historyserver
          persistentVolumeClaim:
            claimName: flink-historyserver-pvc
  job:
    jarURI: local:///opt/flink/jar/flink-wordcount.jar # 使用pv方式挂载jar包
    entryClass: com.liboshuai.demo.FlinkWordCountDemo
    args:   # 传递到作业main方法的参数
      - "--hostname"
      - "master"
      - "--port"
      - "9999"
    parallelism: 1
    upgradeMode: stateless

