controller:
  # 使用 Deployment 部署，这是默认值，但为了明确，我们保留它
  kind: Deployment
  config:
    # 文件传输大小限制
    proxy-body-size: "10G"
  service:
    # 启用外部控制器服务，这将是 MetalLB 负载均衡器暴露的服务
    enabled: true
    # 将外部服务类型设置为 LoadBalancer，MetalLB 会响应该请求并分配 IP
    type: LoadBalancer
    # 如果 MetalLB 配置了 `loadBalancerIP`，你可以在此指定
    # loadBalancerIP: "YOUR_METAL_LB_ALLOCATED_IP" # 可选，如果你想指定一个固定的MetalLB IP
    # 如果你使用了 MetalLB 的 Source Ranges 限制，可以在这里配置
    # loadBalancerSourceRanges:
    #   - 192.168.1.0/24 # 根据你的网络环境修改

  # 根据你的节点操作系统，确保 nodeSelector 设置正确。
  nodeSelector:
    ingress: "true"

  # 建议保留 replicaCount > 1 实现高可用性
  replicaCount: 2 # 示例：设置为2，以实现高可用性
  # 建议配置 PodDisruptionBudget 以确保在节点维护时仍有可用性
  minAvailable: 1 # 确保至少有一个 Pod 可用
  # 或 maxUnavailable: 1 # 确保最多有一个 Pod 不可用

  # 建议为控制器 Pod 设置资源请求/限制，以确保稳定运行
#  resources:
#    requests:
#      cpu: 100m
#      memory: 90Mi
    # limits: # 根据你的集群资源和负载考虑是否设置 limits
    #   cpu: 500m
    #   memory: 500Mi

  # 建议为控制器启用指标导出，以便 Prometheus 抓取
#  metrics:
#    enabled: true
#    service:
#      enabled: true
#    serviceMonitor:
#      enabled: true
#      namespace: monitoring
#      additionalLabels:
#        release: kube-prom-stack
