# -------------------------------------------------------------------
# Helm Chart 的自定义配置值
# 适用于 MetalLB 环境
# -------------------------------------------------------------------

controller:
  # 使用 Deployment 类型，这是 LoadBalancer 模式下的标准做法
  # 你可以根据需要调整副本数量 (replicas)
  kind: Deployment

  # 在 Deployment 模式下，我们不再需要 hostNetwork
  # hostNetwork: false # (这是默认值，可以省略)

  # dnsPolicy 也不再需要特殊设置
  # dnsPolicy: ClusterFirst # (这是默认值，可以省略)

  # 通过节点选择器，将 Ingress Controller Pod 部署到特定的节点上
  # 这仍然是一个好习惯，可以将 Ingress 流量集中在特定节点
  nodeSelector:
    ingress: "true"

  # 配置 Ingress Controller 的 Service
  service:
    # 启用 Service
    enabled: true
    # 关键改动：将 Service 类型设置为 LoadBalancer
    # MetalLB 会检测到这个 Service 并为其分配一个外部 IP 地址
    type: LoadBalancer

    # (可选) 如果你想从 MetalLB 的地址池中指定一个固定的 IP 地址
    # 取消下面的注释并填入你想要的 IP
    # 注意: 这个IP必须在 MetalLB 的 IPAddressPool 配置范围内
    # annotations:
    #   metallb.universe.tf/load-balancer-ip: "192.168.5.200"

# --- 你可以添加以下配置来控制 Deployment 的副本数量 ---
controller.replicaCount: 2 # 例如，运行 2 个 Ingress Controller 实例以实现高可用

