# -------------------------------------------------------------------
# Helm Chart 的自定义配置值
# -------------------------------------------------------------------

# Redis 架构配置
architecture: standalone

# Redis 全局密码配置
# 使用 Base64 编码的密码，或者直接明文（不推荐用于生产）
global:
  redis:
    password: YOUR_PASSWORD # 请替换为你的实际密码

# 主节点配置
master:
  # 持久化配置
  persistence:
    enabled: true
    storageClass: nfs # 替换为你的存储类名称
    size: 8Gi

  # 资源请求与限制
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 2048Mi

# 副本节点配置 (即便 standalone 模式下，也可能存在副本相关的默认配置，这里保留以防万一)
replica:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 2048Mi

# RBAC (Role-Based Access Control) 配置
rbac:
  create: true

# Metrics (Prometheus) 配置
metrics:
  enabled: true
  # ServiceMonitor 配置，用于 Prometheus 自动发现
  serviceMonitor:
    enabled: true
    namespace: monitoring # Prometheus 监控组件所在的命名空间
    labels:
      release: kube-prom-stack # Prometheus Operator 用于发现 ServiceMonitor 的标签值

  # Metrics exporter 的资源请求与限制
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 1024Mi

# 额外的环境变量
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai
