apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: elastic-system
  name: my-es-cluster
spec:
  version: 8.16.1
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
    - name: master-nodes
      count: 1
      config:
        node.roles: ["master"]
      podTemplate:
        spec:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 512m
              memory: 2048Mi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: nfs
    - name: data-nodes
      count: 2
      config:
        node.roles: ["data"]
      podTemplate:
        spec:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 512m
              memory: 2048Mi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: nfs
