#!/usr/bin/env bash

set -e

# --- 加载变量 ---
if [ -f .env ]; then
    source .env
else
    echo "错误: .env 文件不存在!"
    exit 1
fi

# --- 添加仓库并更新 ---
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update

# --- 安装 / 升级 ---
helm upgrade --install "${RELEASE_NAME}" bitnami/elasticsearch \
  --version "${CHART_VERSION}" --namespace "${NAMESPACE}" --create-namespace \
  \
  --set master.replicaCount=1 \
  --set master.masterOnly=false \
  --set data.replicaCount=0 \
  --set coordinating.replicaCount=0 \
  --set ingest.enabled=false \
  \
  --set master.persistence.enabled=true \
  --set-string master.persistence.storageClass="${STORAGE_CLASS_NAME}" \
  --set master.persistence.size=16Gi \
  --set master.resources.requests.cpu=100m \
  --set master.resources.requests.memory=128Mi \
  --set master.resources.limits.cpu=512m \
  --set master.resources.limits.memory=2048Mi \
  --set master.heapSize=1024m \
  \
  --set security.enabled=true \
  --set-string security.elasticPassword="${ELASTIC_PASSWORD}" \
  --set security.tls.restEncryption=true \
  --set security.tls.autoGenerated=true \
  \
  --set copyTlsCerts.resources.requests.cpu=100m \
  --set copyTlsCerts.resources.requests.memory=128Mi \
  --set copyTlsCerts.resources.limits.cpu=256m \
  --set copyTlsCerts.resources.limits.memory=1024Mi \
  \
  --set sysctlImage.resources.requests.cpu=100m \
  --set sysctlImage.resources.requests.memory=128Mi \
  --set sysctlImage.resources.limits.cpu=256m \
  --set sysctlImage.resources.limits.memory=1024Mi \
  \
  --set metrics.enabled=true \
  --set metrics.serviceMonitor.enabled=true \
  --set metrics.serviceMonitor.namespace="${PROMETHEUS_NAMESPACE}" \
  --set metrics.serviceMonitor.labels.release="${PROMETHEUS_RELEASE_LABEL}" \
  --set metrics.resources.requests.cpu=100m \
  --set metrics.resources.requests.memory=128Mi \
  --set metrics.resources.limits.cpu=256m \
  --set metrics.resources.limits.memory=1024Mi
