# -------------------------------------------------------------------
# Helm Chart 的自定义配置值
# -------------------------------------------------------------------

# 架构选择为副本集
architecture: replicaset

# 副本集配置
replicaCount: 3
replicaSetName: "rs0"
# 存储类名称
# global.defaultStorageClass: "nfs" # Bitnami Charts 通常直接在 persistence.storageClass 中配置
persistence:
  size: 16Gi
  storageClass: "nfs" # 使用实际存储类名称

# 认证和安全
auth:
  replicaSetKey: "k/ftJNlwgcIFGjx2GHujlV4yFr9Ee5Qwq59EpfZWNozs/MsSu7BsNOFKDKA2TWmVfzuJ3ybYGajZCt7Vst7Qyff3O3NNOG7/jqLNmUE0x2LN10lD6tARmdCk1WofuPaKbs8uiesiVk+dFXc8mIRlWhuB4WO420FTyHsWlxSVZvV7UNqZcy/oPKk8MuZZuJvQJhkZNW6YeLK7Pn0IOqaGCeRZZNbnDieC9MBf3OEvThoirCsheSpQYiAE1Dp/zDCnf5E0W9uBB/MiXgiHiPqBxjlmC2RkBtYSYDHYzNij41DN+38sdzyHixzE02mWoUU/Wp8BK2i1tkoWhtbtBl2h09cj0xj/43/7rK8pjL625/jooMoD0j3WLsdPV20jYGXyNx8/7q05a+wSqoo7tU/TCECbtskdgH4c/GY9PdOdNnFenOGvL1TCsCnLJS3jE6tsRj+mvKy9xqsAzde+QKbHY7CxQP6Aah5zx400LIjQELYDeqXKG5Xmt1jfKWh1uZQvcD0bDUVJbcNJGe6UUY//0D9woqslcDLZl55lWB/AL7Ndl700s1SFzaDUSmwYjYqFvnYkJoU1PVzTrKu8K7mGzBBRgS97+FXHLvt1y420+AKgHQeFeYU1x8qA3P0Xz7Lb5nDz5mb2IUUwV4bYJjueP+Ixixr78aqYIYKyHtCcKSrVzhAzxA2ycoWDWYzd49emdJrtnWMj5ZNTpXzR4dVm2Br55p7TZRQtVGXC+2nqj+jQ/Icx1rZ7DA0U/n8ne1n0Y/p/0mhbm72lN2Jap0PEf69dWpsiqIRIDtm+hbWMvdwGVpsg0wU6uTklCE7E5U52+YlJzVKjc9+AyKigpd69Igc1A6G25/Nq8eneeBsKwbVSKwyaYaJshtdi77U+xDfLE0fKN0rg787ItQC8cgGPGBZQKZ60TlkoxmbBDD6dIlmA24EQoBq95GgLFyQeWkOn/o3BKkLqGQPmy9qX2eRW+W/MHIkfHvkT2T8NKJLZkpvfjHNQ"
  rootPassword: "YOUR_PASSWORD"
  databases:
    - "test"
  usernames:
    - "lbs"
  passwords:
    - "YOUR_PASSWORD"

# Pod 反亲和性设置，确保副本分散在不同节点
podAntiAffinityPreset: soft

# 资源请求与限制
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 512m
    memory: 2048Mi

arbiter:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 2048Mi

# RBAC (Role-Based Access Control)
rbac:
  create: true

# Prometheus 监控配置
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    # Prometheus Operator 所在的命名空间
    namespace: "monitoring"
    # Prometheus Operator 用于发现 ServiceMonitor 的标签值
    labels:
      release: "kube-prom-stack" # 你的 kubectl get all 输出中release名称为 kube-prom-stack
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 1024Mi

# 额外的环境变量
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai

